apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-nodejs
  template:
    metadata:
      labels:
        app: hello-world-nodejs
    spec:
      containers:
        - name: hello-world-nodejs
          image: hello-world-nodejs:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "test"
